// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tanheksftpmckhbhpzps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbmhla3NmdHBtY2toYmhwenBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTExNjIsImV4cCI6MjA2OTk4NzE2Mn0.-C0Bmh-rKCic9M6LuQOaXQhwwWVZSc4CHthVLM9f0L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});